driver_names = {
    "Max Verstappen": "VER",
    "Sergio Pérez": "PER",
    "Sergio Perez": "PER",
    "Fernando Alonso": "ALO",
    "Carlos Sainz": "SAI",
    "Lewis Hamilton": "HAM",
    "Lance Stroll": "STR",
    "George Russell": "RUS",
    "Valtteri Bottas": "BOT",
    "Pierre Gasly": "GAS",
    "Alexander Albon": "ALB",
    "Yuki Tsunoda": "TSU",
    "Logan Sargeant": "SAR",
    "Kevin Magnussen": "MAG",
    "Nyck de Vries": "DEV",
    "Nyck De Vries": "DEV",
    "Nico Hülkenberg": "HUL",
    "Nico Hulkenberg": "HUL",
    "Guanyu Zhou": "ZHO",
    "Lando Norris": "NOR",
    "Esteban Ocon": "OCO",
    "Charles Leclerc": "LEC",
    "Oscar Piastri": "PIA",
    "Daniel Ricciardo":"RIC",
    "Liam Lawson":"LAW"
}