stations = {
  "Bahrain Grand Prix":"41150",
  "Saudi Arabian Grand Prix":"41020",
  "Australian Grand Prix":"94865",
  "Azerbaijan Grand Prix":"37864",
  "Miami Grand Prix":"1",
  "Emilia Romagna Grand Prix":"1",
  "Monaco Grand Prix":"1",
  "Spanish Grand Prix":"1",
  "Canadian Grand Prix":"1",
  "Austrian Grand Prix":"1",
  "British Grand Prix":"1",
  "Hungarian Grand Prix":"1",
  "Belgian Grand Prix":"1",
  "Dutch Grand Prix":"1",
  "Italian Grand Prix":"1",
  "Singapore Grand Prix":"1",
  "Japanese Grand Prix":"1",
  "Qatar Grand Prix":"1",
  "United States Grand Prix":"1",
  "Mexican Grand Prix":"1",
  "Brazilian Grand Prix":"1",
  "Las Vegas Grand Prix":"1",
  "Abu Dhabi Grand Prix":"1"
}